---
title: "Predicting risk of Coronary Heart Disease using Machine Learning"
author: "Dennis Wiersma"
date: "2022-10-05"
urlcolor: blue
output: 
  pdf_document: 
    highlight: kate
    number_sections: yes
    citation_package: natbib
    
    includes: 
      in_header: preamble.tex
      before_body: prefix.tex
      
bibliography: references.bib
---

```{r, include=FALSE}
# Copyright (c) 2022 Dennis Wiersma.
# Licensed under GPLv3. See LICENSE file.
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Excludes all code from the report
knitr::opts_chunk$set(include = FALSE)
```

```{r loadingDataset}
# Load dataset
dataset <- read.table(file = "../data/processedData.csv", header = TRUE, sep = ",", stringsAsFactors = TRUE)
```

\newpage


# Introduction
\newpage

# Methods
\newpage

# Results
## Data acquisition & preprocessing

## Validation & Performance

## Research findings

\newpage

# Conclusion & Discussion

## Result based conclusions

## Discussion

## General conclusions and perspective

\newpage

# Bibliography

[@Michiel_Noback_2022_hanze]
